name: ColorfulCommands
main: de.themoep.ColorfulCommands.ColorfulCommands
version: 0.1.1
description: Provides a wrapper command to use color codes in every command
author: Phoenix616
website: www.themoep.de
commands:
   cc:
      aliases: [colorcommand, convertcolors]
      description: Wrapper command
      usage: /<command> command arguments
      permission: colorfulcommands.use
      permission-message: You don't have the permission <permission>
permissions:
   colorfulcommands.use:
      description: Gives permission to the command
      default: op